# Generated by Django 4.1 on 2022-08-14 05:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_rename_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
